name: Generate Documents
on:
  workflow_run:
    workflows: ["Deploy Static Site!"] # Run static.yml file first then do this one...branches: 
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo "The previous workflow succeeded!"
      
  convert_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Markdown to PDF and HTML
        uses: BaileyJM02/markdown-to-pdf@v1.2.0
        with:
          input_path: MData/               # Folder where your .md files are
          output_dir: afacts/             # Where to save the results
          build_html: true                # Also generate HTML
          build_pdf: true                 # Also generate PDF
          table_of_contents: true

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: converted-documents
          path: afacts/
