name: Generate Documents
on: [push]

jobs:
  convert_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Convert Markdown to PDF/HTML
        uses: BaileyJM02/markdown-to-pdf@v1
        with:
          input_path: MData/               # Folder where your .md files are
          output_dir: MData/output/             # Where to save the results
          build_html: true                # Also generate HTML
          build_pdf: true                 # Also generate PDF
          table_of_contents: true

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: converted-documents
          path: output/
